title: Hayden Bean # your name (or website title) here
logo: "/images/IMG_9168.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Proven leader, team player, and a graduate of Babson College. Excellent problem-solving skills, strong work ethic, and coachability. Punctual, conscientious, and courteous to customers and colleagues alike.
  <br><br>
  Email: hbean2009@gmail.com 
  <br><br>
  Phone: (781)-835-5141 
  <br><br>
  <a href="https://www.linkedin.com/hayden-bean/">LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
